---
name: "TeleJelly"
guid: "4b71013d-00ba-470c-9e4d-0c451a435328"
version: "1.0.0.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "A Plugin for logging into Jellyfin using the Telegram Login Widget"
description: >
  This Plugin allows logging into Jellyfin using the Telegram Login Widget as a "SSO" provider.
  The plugin requires assinging a telegram user to one or more virtual groups in order for them to Login.
  Each group can then have access to all or specified Jellyfin-folders.
category: "Authentication"
owner: "hexxone"
artifacts:
- "TeleJelly.dll"
changelog: >
  changelog
